Add first implementation
approvers/members-db-rust pull request #1
Opened 2020-06-30 14:14 UTC by Siketyan

2020-06-30 14:15 UTC, Colk-tech approved these changes
読めないけど
***†   無   責   任   A   p   p   r   o   v   e   †***

2020-06-30 14:32 UTC, isso0424 approved these changes
マクロ以外ヨシ!!!
***APPROVE***

2020-06-30 14:32 UTC, isso0424 commented on src/database.rs
> +
1回しか使ってないしマクロである意味なくね...?

2020-06-30 14:36 UTC, Siketyan commented on src/database.rs
> +
eea880a

2020-06-30 14:36 UTC, kawaemon commented
レビューしたいんですけど今死ぬほど忙しいのでもう少し待ってください。。。

2020-06-30 14:36 UTC, Siketyan commented
急がないのでいつでも 😉

2020-06-30 14:53 UTC, MikuroXina requested changes
無責任 Request Changes

2020-06-30 14:53 UTC, MikuroXina commented on src/database.rs
> +    pub members: Vec<Member>,
`pub` しないようにしてください
```suggestion
    members: Vec<Member>,
```

2020-06-30 14:53 UTC, MikuroXina commented on src/main.rs
> +    pub command: Command,
`pub` が消せる気がする(間違ってたらすまない
```suggestion
    command: Command,
```

2020-06-30 14:53 UTC, MikuroXina commented on src/server.rs
> +    Json(members.clone())
これじゃダメなんすか
```suggestion
    Json(state.members)
```

2020-06-30 14:54 UTC, Siketyan commented on src/database.rs
> +    pub members: Vec<Member>,
Getter つくればいいのですか……？

2020-06-30 15:22 UTC, kawaemon commented on Cargo.toml
> +rocket_contrib = "*"
バージョン指定をお願いします。。。cargo editを使えば比較的簡単に出来ます

2020-06-30 15:22 UTC, kawaemon commented on src/server.rs
> +    Json(members.clone())
`state.members.clone()` ですかね

2020-06-30 15:22 UTC, kawaemon commented on src/main.rs
> +extern crate rocket;
最近のRustのアップデートで必要なくなったはずです

2020-07-01 01:07 UTC, Siketyan commented on src/main.rs
> +extern crate rocket;
消したら動かなくなりました
![image](https://user-images.githubusercontent.com/12772118/86191697-acf37380-bb82-11ea-898f-936d626580aa.png)

2020-07-01 01:09 UTC, Siketyan commented on Cargo.toml
> +rocket_contrib = "*"
![image](https://user-images.githubusercontent.com/12772118/86191806-f80d8680-bb82-11ea-98e3-b93bb16a4864.png)

2020-07-01 01:10 UTC, kawaemon commented on Cargo.toml
> +rocket_contrib = "*"
https://qiita.com/i2tsuki/items/8d90f7aa872671404a15

こちらを

2020-07-01 01:11 UTC, kawaemon commented on src/main.rs
> +extern crate rocket;
`use rocket::routes` などをすればいけるとおもいます

2020-07-01 01:12 UTC, Siketyan commented on src/server.rs
> +    Json(members.clone())
478c7e7

2020-07-01 01:13 UTC, Siketyan commented on src/main.rs
> +extern crate rocket;
678ab1b

2020-07-01 01:14 UTC, Siketyan commented on Cargo.toml
> +rocket_contrib = "*"
なるほど……
とりあえず手動で書きました 
478c7e7

2020-07-01 01:15 UTC, Siketyan commented on src/main.rs
> +    pub command: Command,
6f52936

2020-07-01 01:15 UTC, kawaemon commented on src/database.rs
> +    pub members: Vec<Member>,
pubだと変更も出来てしまうので、getterを作るのが適切かと思います。（Rustにreadonlyはないです。。。それを擬似的に実現するライブラリはありますが）

2020-07-01 02:29 UTC, Siketyan commented on src/database.rs
> +    pub members: Vec<Member>,
AddCommand で push するときに mut での借用を要求してきます……

2020-07-01 02:31 UTC, MikuroXina commented on src/database.rs
> +    pub members: Vec<Member>,
`Database` に `members` へ追加するようなメソッドを実装するのはダメですか?

2020-07-01 02:35 UTC, Siketyan commented on src/database.rs
> +    pub members: Vec<Member>,
そうしました 40b738a

2020-07-01 02:38 UTC, MikuroXina approved these changes

2020-07-01 04:40 UTC, kawaemon approved these changes

2020-07-01 04:43 UTC, merged