Setup CI workflows
approvers/members-db-rust pull request #7
Opened 2020-07-02 06:53 UTC by Siketyan

Closes #3

2020-07-02 08:53 UTC, kawaemon approved these changes

2020-07-02 08:53 UTC, kawaemon commented on .github/workflows/rust.yaml
> +        run: cargo test --verbose
https://github.com/approvers/MeigenBot-Rust/blob/master/.github/workflows/main.yml
のようにRust ClippyというLinterを走らせるともっと幸せになれます。多分。

2020-07-02 09:04 UTC, Siketyan commented on .github/workflows/rust.yaml
> +        run: cargo test --verbose
d50a803

2020-07-02 21:25 UTC, kawaemon requested changes

2020-07-02 21:25 UTC, kawaemon commented on .github/workflows/rust.yaml
> +          args: --verbose
testとclippyでbuildが走るので、これ要らないと思います

2020-07-03 00:05 UTC, Siketyan commented on .github/workflows/rust.yaml
> +          args: --verbose
明示的に build したかったので順番変えました 937b066

2020-07-03 00:06 UTC, kawaemon approved these changes

2020-07-03 00:06 UTC, merged